### ISSUE TITLE
7- Levantamento de algum tratamento da informação.

### ISSUE THREAD

**Issue by GuilhermeSpaolonzi** [GuilhermeSpaolonzi/PowerBI#17]

**Comment by rsilveirasuzano** [comment]
Tratamentos:

-Cliente: Somente clientes com mesmo numero da conta credito
-$ Contas a Receber: Montante doc em BRL  e Montante doc em USD (para ME)
-Classe de Risco do cliente: Seleção somente das classes A, B, C, D e E (e derivados - Ex: A, A+ e A-)
-Produto: Seleção somente dos clientes de Papel, Celulose e Bens de Consumo
-Segmento: Papel > Grandes Contas, Pulverizado ou Micropulverizado. Para Celulose e Bens de Consumo não tem classificação
-Tipo de venda: Papel > Gráfico/Cutsize. Para Celulose e Bens de Consumo não tem classificação
-Mercado	: ME ou MI

<https://suzano.sharepoint.com/:x:/r/sites/Credito/Documentos%20Compartilhados/Relatorios/Ficha%20de%20indicadores.xlsx?d=w1219fcbfef924a17930e46b980fe1eed&csf=1&e=QGaUux>
