### ISSUE TITLE
6-Identificação e definição dos conceitos necessários.

### ISSUE THREAD

**Issue by GuilhermeSpaolonzi** [GuilhermeSpaolonzi/PowerBI#18]

**Comment by rsilveirasuzano** [comment]
Definição de alto risco:

Classe de   Risco | Tipo de risco
-- | --
A+ | 1 baixo risco
A | 1 baixo risco
A- | 1 baixo risco
B+ | 1 baixo risco
B | 1 baixo risco
B- | 1 baixo risco
C+ | 1 baixo risco
C | 1 baixo risco
C- | 2 Alto risco
D+ | 2 Alto risco
D | 2 Alto risco
D- | 2 Alto risco
