### ISSUE TITLE
5- Identificação de fontes de cada informação

### ISSUE THREAD

**Issue by GuilhermeSpaolonzi** [GuilhermeSpaolonzi/PowerBI#4]

**Comment by rsilveirasuzano** [comment]
Fontes identificadas - info na ficha de credito

Informação	Fonte	
Cliente	BW Contas a Receber (Conta de credito)	
$ Contas a Receber	BW Contas a Receber (Montante do doc)	
Classe de Risco do cliente	BW Contas a receber (FDK43)	
Produto	Super DE-PARA (que vem do BW Receitas e de histórico)	
Segmento	Super DE-PARA (que vem do BW Receitas e de histórico)	
Tipo de venda	Super DE-PARA (que vem do BW Receitas e de histórico)	
Mercado	BW Contas a receber (Mercado)	
Regional	BW Cliente Novo (regional)	
Coordenador	BW Cliente Novo (atributo do vendedor externo)	
Vendedor	BW Cliente Novo (vendedor externo)
